// <auto-generated />
using Blazor.DynamicTable.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.DynamicTable.Migrations
{
    [DbContext(typeof(DynamicTableDBContext))]
    [Migration("20201028134445_Init_DataBase")]
    partial class Init_DataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor.DynamicTable.Context.DynamicTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("TableProperty")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.ToTable("DynamicTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Table customer",
                            TableName = "Customers",
                            TableProperty = "[{\"Name\":\"Id\",\"Type\":1,\"IsIndentity\":true,\"MaxLenght\":0},{\"Name\":\"Name\",\"Type\":2,\"IsIndentity\":false,\"MaxLenght\":255},{\"Name\":\"Birthday\",\"Type\":3,\"IsIndentity\":false,\"MaxLenght\":0}]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
